message: Success Message in feign-client-prod.yml

server:
  port: 8081

app:
  id: ${random.uuid}

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

spring:
  application:
    name: user-api
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-connect-timeout-seconds: 5
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    eureka-connection-idle-timeout-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"