---
app:
  id: "${random.uuid}"
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: "http://${eureka.instance.hostname}:8761/eureka/"
  instance:
    hostname: localhost
server:
  port: 8888
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: "lb://ORDER-SERVICE"
          predicates:
            - Path=/order/**

        - id: payment-service
          uri: "lb://PAYMENT-SERVICE"
          predicates:
           - Path=/payment/**

