server:
  port: 8761

spring:
  application:
    name: eureka-server

 client:
  fetch-registry: false
  register-with-eureka: false
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      company:
        eurekaserver: INFO
