server:
  port: 8888

spring:
 application:
  name: config-server
 cloud:
  config:
   server:
    git:
     uri: https://github.com/YadigarAlakbarli/spring-cloud-microservices-architecture
     search-paths:
      - "config-repo/*configs"

eureka:
 instance:
  hostname: localhost
 client:
  eureka-server-port: 8761
  fetch-registry: true
  register-with-eureka: true
  serviceUrl:
   defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka/

management:
 endpoints:
  web:
   exposure:
    include: "*"